name: Code Quality Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint-and-links:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up Python (change version as needed)
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8

    #   - name: Run flake8 linter
    #     run: |
    #       flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

      # Broken link check for README
      - name: Check broken links in README
        uses: lycheeverse/lychee-action@v1.9.2
        with:
          args: README.md --verbose --no-progress
